using System;
using System.Collections.Generic;
using System.Linq;

namespace VacunacionCovid
{
    class Program
    {
        // ─────────────────────────────────────────────────────────────────
        //  Lista de 500 ciudadanos ecuatorianos (ficticios)
        // ─────────────────────────────────────────────────────────────────
        static readonly string[] CIUDADANOS_ECUADOR = {
            "Abigail Acosta Febres",
            "Abigail Endara Caiza",
            "Adriana Izquierdo Vega",
            "Adriana Llumiquinga Papue",
            "Adriana Naranjo Díaz",
            "Adriana Viteri Narváez",
            "Agustín Figueroa Loja",
            "Agustín Palacios Tobar",
            "Agustín Quezada Rivadeneira",
            "Agustín Quinde Pilataxi",
            "Agustín Tapia Pérez",
            "Alejandra Freire Maldonado",
            "Alex Campaña Pacari",
            "Alex Dávila Cerda",
            "Alex Guacho Alvarado",
            "Alexis Delgado Proaño",
            "Alexis Guerrero Cevallos",
            "Alfredo Izquierdo Gómez",
            "Alfredo Mora Delgado",
            "Alfredo Sarango Sánchez",
            "Alfredo Zambrano Iza",
            "Alicia Granda Loja",
            "Alicia Palacios Rivadeneira",
            "Amparo Cortés Zambrano",
            "Amparo Ponce Nieto",
            "Amparo Rivera Alcívar",
            "Ana Cristina Campaña Tamayo",
            "Ana Cristina Encalada Barahona",
            "Ana Cristina Proaño Mosquera",
            "Ana Gallegos Freire",
            "Andrea Espinoza Palacios",
            "Andrea Mosquera Llumiquinga",
            "Andrea Pazmiño Villacís",
            "Andrea Uribe Sotomayor",
            "Andrés Figueroa Chimbo",
            "Andrés Lema Dávila",
            "Andrés Rivadeneira Viteri",
            "Angélica Feijoo Ochoa",
            "Angélica Rodríguez Ordóñez",
            "Antonio Guamán Rodríguez",
            "Antonio Quinde Feijoo",
            "Antonio Vargas Pazmiño",
            "Antonio Villacís Conterón",
            "Beatriz Armijos Tamayo",
            "Beatriz Conterón Llumiquinga",
            "Beatriz Holguín Carrasco",
            "Beatriz Uribe Játiva",
            "Benjamín Briones Méndez",
            "Benjamín Ochoa Zabala",
            "Berta Reinoso Acosta",
            "Blanca Hidalgo Feijoo",
            "Blanca Macías Intriago",
            "Blanca Mosquera Quinde",
            "Blanca Obando Quishpe",
            "Bolívar Izquierdo Ordóñez",
            "Bolívar Villacís Mendoza",
            "Bolívar Villacís Noboa",
            "Bryan Cashpa Tamayo",
            "Bryan Cujilán Quezada",
            "Bryan Tapia Proaño",
            "Byron Guamán Iza",
            "Byron Ordóñez Papue",
            "Byron Rivadeneira Sarango",
            "Camila Cashpa Guevara",
            "Camila Quezada Terán",
            "Camila Tobar Rodas",
            "Camilo Cortés Suárez",
            "Camilo Herrera Freire",
            "Camilo Mora Huatatoca",
            "Camilo Reinoso Gallegos",
            "Carlos Briones Lazo",
            "Carlos Cuji Cashpa",
            "Carlos Quiñónez Ulloa",
            "Carmen Salinas Mendoza",
            "Cecilia Cujilán Sotomayor",
            "Cecilia González Pacari",
            "Cecilia Lazo Jumbo",
            "Cecilia Neira Holguín",
            "Cecilia Spotorno Rodas",
            "Christian Guerrero Gómez",
            "Christian Tapia Acosta",
            "Clara Andrade Sotomayor",
            "Clara Carrasco Grijalva",
            "Clara Robles Caiza",
            "Clara Zambrano Vera",
            "Claudio Izquierdo Jumbo",
            "Claudio Ordóñez Terán",
            "Claudio Terán Rodríguez",
            "Consuelo Conterón Guamán",
            "Consuelo Ochoa Calderón",
            "Consuelo Viteri Tobar",
            "Cristian Calderón Spotorno",
            "Cristian Intriago Endara",
            "Cristian Shiguango Freire",
            "Cristina Albán Puga",
            "Cristina Morales Jara",
            "Cristina Rivadeneira Delgado",
            "César Albán Tapia",
            "César Gómez Quinde",
            "César Sacoto Toapanta",
            "Daniela Huatatoca Sánchez",
            "Darwin Aranda Amaguaña",
            "Darwin Aranda Suárez",
            "Darwin Huatatoca Jara",
            "Darwin Méndez Quishpe",
            "Darwin Obando Calderón",
            "Darío Acosta Bastidas",
            "Darío Campaña Sacoto",
            "Darío Robles Rivera",
            "David Barahona Castro",
            "David Granda Jumbo",
            "David Toapanta Viteri",
            "Dayana Cueva Alcívar",
            "Dayana Grijalva Cando",
            "Dayana Robles Llumiquinga",
            "Dayana Salinas Bustamante",
            "Delia Armijos Molina",
            "Delia Ramos Sánchez",
            "Delia Shiguango Terán",
            "Diana Vega Reinoso",
            "Diego Alcívar Rivadeneira",
            "Diego Delgado Feijoo",
            "Diego Hidalgo Lazo",
            "Diego Maldonado Romero",
            "Diego Papue Figueroa",
            "Diego Yánez Intriago",
            "Edison Shiguango Morales",
            "Eduardo Endara Aranda",
            "Eduardo Figueroa Castro",
            "Efraín Cabrera Campaña",
            "Efraín Conterón López",
            "Efraín Jumbo Terán",
            "Elena Cashpa Chávez",
            "Elena Huatatoca Andrade",
            "Elena Iza Martínez",
            "Elena Romero Morales",
            "Emilio Endara Bastidas",
            "Emilio Guamán Salinas",
            "Emilio Gómez García",
            "Emilio Gómez Vega",
            "Ernesto Abad Albán",
            "Ernesto Cando Lema",
            "Ernesto Guamán Sánchez",
            "Ernesto Robles Pintado",
            "Esperanza Campaña Armijos",
            "Esperanza Encalada González",
            "Esperanza Lema Loja",
            "Esperanza Papue Guevara",
            "Esperanza Pazmiño Rodríguez",
            "Esperanza Proaño Baquero",
            "Esperanza Pérez Maldonado",
            "Esteban Ortiz Hidalgo",
            "Esteban Reyes Chimbo",
            "Estela Loor Ramos",
            "Estela Yépez Quispe",
            "Evelyn Alvarado Espín",
            "Evelyn Zabala Gómez",
            "Fabiola Reinoso Feijoo",
            "Fabiola Rodas Alvarado",
            "Fabián Alvarado Encalada",
            "Fabián Baquero Lazo",
            "Fabián Cashpa Hidalgo",
            "Fabián Morales Acosta",
            "Fabián Morocho Cevallos",
            "Fabián Rivadeneira Vega",
            "Fabricio Benalcázar Iza",
            "Fabricio Lema Albán",
            "Fabricio Villacís Figueroa",
            "Felipe Figueroa Mora",
            "Felipe Guacho Narváez",
            "Felipe Suárez Granda",
            "Felipe Torres Baquero",
            "Fernanda Alvarado Conterón",
            "Fernanda Espín Ponce",
            "Fernando Cortés Figueroa",
            "Fernando Dávila Pilataxi",
            "Fernando Freire Cueva",
            "Fernando Mendoza Proaño",
            "Fernando Suárez Játiva",
            "Flor Chuqui Maldonado",
            "Flor Ulloa Yépez",
            "Florencia Cabrera Uribe",
            "Florencia Guevara Andrade",
            "Florencia Maldonado Encalada",
            "Franco Iza Tobar",
            "Franco Mora Cashpa",
            "Franco Reyes Martínez",
            "Franco Rivadeneira Ochoa",
            "Freddy Briones Villacís",
            "Freddy Lazo Suárez",
            "Gabriel Conterón Gallegos",
            "Gabriel Guevara Barahona",
            "Gabriel Obando Loja",
            "Gabriel Simbaña Paredes",
            "Gabriel Torres Guevara",
            "Gabriela Chuqui Cortés",
            "Gabriela Cortés Feijoo",
            "Gabriela Lema Hidalgo",
            "Gabriela Rivadeneira Carrasco",
            "Galo Armijos Sotomayor",
            "Galo Baquero Puga",
            "Galo Cevallos Viteri",
            "Galo Conterón Lema",
            "Galo Freire Delgado",
            "Galo Nieto Terán",
            "Galo Ulloa Sarango",
            "Gerardo Bustamante Abad",
            "Gerardo Cando Conterón",
            "Giovanna Cárdenas Sotomayor",
            "Giovanna Llumiquinga Tapia",
            "Giovanna Ortiz Abad",
            "Giovanna Quiñónez Andrade",
            "Gladys Llumiquinga Pilataxi",
            "Gladys Narváez Toapanta",
            "Gladys Terán Gómez",
            "Gladys Yánez Sarango",
            "Gloria Guerrero Rivera",
            "Gloria Holguín Suárez",
            "Gonzalo Conterón Martínez",
            "Gonzalo Spotorno Suárez",
            "Gonzalo Villacís Vera",
            "Graciela García Pacari",
            "Graciela Intriago Mendoza",
            "Gregorio Aranda Viteri",
            "Gregorio Mueckay Pacari",
            "Gregorio Pacari Alvarado",
            "Gustavo Chuqui Baquero",
            "Gustavo Guacho Cortés",
            "Gustavo Gómez Flores",
            "Gustavo Molina Cotacachi",
            "Gustavo Nieto Naranjo",
            "Helena Alcívar Ordóñez",
            "Helena Guacho Noboa",
            "Helena Rivera Pintado",
            "Henry Reyes Morales",
            "Henry Romero Mendoza",
            "Hilda Andrade Armijos",
            "Hilda Cruz Yánez",
            "Hilda Matamoros Espín",
            "Homero Viteri Figueroa",
            "Hugo Grijalva Sánchez",
            "Hugo Suárez Granda",
            "Héctor Cruz Chuqui",
            "Héctor Quiñónez Mueckay",
            "Héctor Sánchez Salinas",
            "Inés Cotacachi Ullauri",
            "Inés Holguín Mendoza",
            "Inés Paredes Delgado",
            "Inés Salazar Paredes",
            "Inés Ulloa Molina",
            "Irene Aranda Endara",
            "Irene Rivera Cando",
            "Isabel Lema Cevallos",
            "Isabel Lema Cruz",
            "Isabel Uribe Puga",
            "Ismael Castro Acosta",
            "Ismael Cerda Herrera",
            "Ismael Granda Tapia",
            "Iván Barahona Grijalva",
            "Iván Nieto Torres",
            "Iván Quinde Cabrera",
            "Janeth Benalcázar Espinoza",
            "Janeth Calderón Huatatoca",
            "Janeth Cuji Vera",
            "Janeth Espín Obando",
            "Janeth Feijoo Guerrero",
            "Janeth Herrera Quiñónez",
            "Javier Guamán García",
            "Javier Ordóñez Villacís",
            "Javier Pacari Mosquera",
            "Javier Pazmiño Guerrero",
            "Javier Simbaña Viteri",
            "Jimmy Pintado Uribe",
            "Jonathan Chimbo Cando",
            "Jonathan Mueckay Hidalgo",
            "Jonathan Narváez Alcívar",
            "Jonathan Quispe Huatatoca",
            "Jorge Acosta Rivadeneira",
            "Jorge Díaz Ramos",
            "Jorge Espín López",
            "Jorge Herrera Mendoza",
            "Jorge Quinde Andrade",
            "José Bustamante Quiñónez",
            "José Mendoza Cevallos",
            "José Palacios Cevallos",
            "José Simbaña Paredes",
            "Juan Jara Vera",
            "Juan Matamoros Pintado",
            "Karina Bastidas Cuji",
            "Karina Guacho Suárez",
            "Karina Guamán Ortiz",
            "Karina Matamoros Reinoso",
            "Karina Nieto Hidalgo",
            "Karina Ponce Lema",
            "Karina Suárez Caiza",
            "Karla Quezada Morocho",
            "Kevin Cueva Salinas",
            "Kevin Lazo Vega",
            "Kevin Salinas Viteri",
            "Leonardo Abad Carrasco",
            "Liliana Llumiquinga Martínez",
            "Liliana Reyes Villacís",
            "Liliana Sarango Ochoa",
            "Liliana Terán Ortiz",
            "Lorena Papue Martínez",
            "Lorena Papue Shiguango",
            "Lorena Sacoto Guerrero",
            "Lorenzo Chimbo Cruz",
            "Lorenzo Encalada Molina",
            "Lorenzo Salinas Lazo",
            "Lourdes Acosta Salazar",
            "Lourdes Alvarado Pilataxi",
            "Lourdes Chávez Ulloa",
            "Lourdes Hidalgo Pérez",
            "Lucho Barahona Dávila",
            "Lucía Amaguaña García",
            "Lucía Mora Cerda",
            "Luis Cujilán Carrasco",
            "Luis Huatatoca Díaz",
            "Manuel Molina Mendoza",
            "Manuel Neira Rodríguez",
            "Manuel Pérez Conterón",
            "Manuel Suárez Mosquera",
            "Manuel Viteri Pazmiño",
            "Marcelo Chuqui Huatatoca",
            "Marcelo Tamayo Cashpa",
            "Marco Dávila Holguín",
            "Marco Ochoa Noboa",
            "Mariana Sotomayor Cevallos",
            "Marisol Cerda Vera",
            "Marisol Holguín Pazmiño",
            "Mariuxi Figueroa Viteri",
            "Mariuxi Flores Villacís",
            "Mariuxi Salinas Reinoso",
            "Mariuxi Tamayo Pilataxi",
            "Martha Aranda Chimbo",
            "Martha Delgado Neira",
            "Martha Suárez Llumiquinga",
            "María Játiva Loor",
            "María Nieto Izquierdo",
            "Mateo Febres Pacari",
            "Mateo Proaño Morocho",
            "Mateo Quiñónez Gallegos",
            "Mateo Sotomayor Nieto",
            "Mateo Zabala Grijalva",
            "Mauricio Endara Molina",
            "Mauricio Pilataxi García",
            "Mauricio Quispe Bastidas",
            "Mauricio Sotomayor Amaguaña",
            "Miguel Mendoza Tapia",
            "Miguel Yépez Cruz",
            "Miryam Calderón Quispe",
            "Mishel García Encalada",
            "Mishel Izquierdo Huatatoca",
            "Mishel Proaño Ullauri",
            "Mónica Armijos Cabrera",
            "Mónica Briones Calderón",
            "Mónica Grijalva Alvarado",
            "Mónica Terán Tamayo",
            "Mónica Villacís Loor",
            "Mónica Viteri Cando",
            "Napoleón Aguirre Vega",
            "Napoleón Jara Lazo",
            "Napoleón Sarango Maldonado",
            "Natalia Andrade Quishpe",
            "Natalia Cotacachi Vera",
            "Natalia Cruz Reinoso",
            "Natalia Mueckay Chávez",
            "Natalia Torres Campaña",
            "Nathaly Barahona Játiva",
            "Nathaly Narváez Cashpa",
            "Nelson Díaz Pacari",
            "Nelson Suárez Conterón",
            "Nicolás Bustamante Bastidas",
            "Nicolás Lema Proaño",
            "Nicolás Mueckay Hidalgo",
            "Nicolás Naranjo Calderón",
            "Nicolás Neira Guacho",
            "Nicolás Obando Shiguango",
            "Nicolás Zambrano Freire",
            "Norma Alvarado Méndez",
            "Norma Díaz Alvarado",
            "Norma Yépez Quezada",
            "Octavio Barahona Quinde",
            "Octavio Lazo Gómez",
            "Octavio Nieto Amaguaña",
            "Octavio Ulloa Nieto",
            "Olga Espín Alvarado",
            "Olga Matamoros Sotomayor",
            "Olga Simbaña Sánchez",
            "Omar Cashpa Maldonado",
            "Omar Cotacachi Bastidas",
            "Omar Macías Pintado",
            "Omar Ortiz Aranda",
            "Oswaldo Alcívar Bastidas",
            "Oswaldo Narváez Intriago",
            "Pablo Cabrera Quinde",
            "Pablo Guerrero Cevallos",
            "Pablo Paredes Febres",
            "Pablo Puga Terán",
            "Paco Espín Castro",
            "Paco Granda Endara",
            "Pamela Flores Sacoto",
            "Pamela Palacios Morales",
            "Pancho Cabrera Neira",
            "Pancho Suárez Zambrano",
            "Paola Campaña Encalada",
            "Paola Espinoza Tobar",
            "Paola Guamán Endara",
            "Paola Paredes Rivera",
            "Paola Quezada Yépez",
            "Paquita Mueckay Lema",
            "Paquita Sacoto Suárez",
            "Patricia Ordóñez Gallegos",
            "Patricia Pacari Méndez",
            "Patricia Quiñónez Pilataxi",
            "Patricio Baquero Andrade",
            "Patricio Guamán Cevallos",
            "Patricio Guerrero Endara",
            "Patricio Herrera Mueckay",
            "Patricio Viteri Dávila",
            "Pilar Cashpa Lazo",
            "Pilar Dávila Obando",
            "Pilar Ordóñez Reyes",
            "Pilar Ponce Cotacachi",
            "Pilar Sotomayor Loja",
            "Pilar Terán Narváez",
            "Priscila Endara Zambrano",
            "Rafael Quiñónez Villacís",
            "Rafael Rodas Chávez",
            "Ramiro Lema Matamoros",
            "Ramiro Shiguango Loja",
            "Raúl Barahona Ochoa",
            "Raúl Cevallos Cashpa",
            "Raúl Espinoza Pintado",
            "Rebeca Barahona Hidalgo",
            "Rebeca Morales Andrade",
            "Rebeca Viteri Jumbo",
            "René Yépez Neira",
            "Ricardo Aranda Guerrero",
            "Ricardo Pilataxi Nieto",
            "Ricardo Quinde Yánez",
            "Roberto Barahona Feijoo",
            "Roberto Sacoto Proaño",
            "Rodrigo Macías Simbaña",
            "Rosa Andrade Sacoto",
            "Rosa Yánez Vera",
            "Rosa Zabala Dávila",
            "Rubén Bastidas Ortiz",
            "Rubén Campaña Rivera",
            "Rubén Obando Cuji",
            "Sandra Armijos Mendoza",
            "Sandra Mueckay Romero",
            "Santiago Cabrera Viteri",
            "Santiago Nieto Loor",
            "Santiago Reyes Sotomayor",
            "Santiago Sacoto Alcívar",
            "Sebastián Feijoo Armijos",
            "Sebastián Loja Holguín",
            "Silvia Alcívar Holguín",
            "Silvia Armijos Grijalva",
            "Silvia Lazo Salinas",
            "Silvia Loor López",
            "Sofía Obando Carrasco",
            "Sofía Rivera Quinde",
            "Sofía Shiguango Robles",
            "Stefany Cotacachi Terán",
            "Steven Campaña Lazo",
            "Steven Cujilán Zambrano",
            "Susana Encalada Carrasco",
            "Susana Feijoo Loja",
            "Susana García Lazo",
            "Susana López Quispe",
            "Susana Reinoso Nieto",
            "Susana Sacoto Lazo",
            "Susana Sarango Pintado",
            "Teresa González Ramos",
            "Teresa Shiguango Dávila",
            "Valeria Jumbo Granda",
            "Verónica Caiza Pacari",
            "Viviana Reinoso Cotacachi",
            "Viviana Sotomayor Hidalgo",
            "Viviana Vega Andrade",
            "Viviana Vera Granda",
            "Víctor Guevara Izquierdo",
            "Víctor Sotomayor Conterón",
            "Víctor Yánez Izquierdo",
            "Wilmer Holguín Mueckay",
            "Wilmer Lazo Llumiquinga",
            "Wilmer Mosquera Paredes",
            "Wilmer Ulloa Romero",
            "Wilmer Zabala Cerda",
            "Xavier Benalcázar Freire",
            "Xavier Cashpa Chávez",
            "Xavier Espín Salinas",
            "Xavier Jara Maldonado",
            "Xavier Lema Pilataxi",
            "Xavier Mendoza Nieto",
            "Xavier Neira Bastidas",
            "Yolanda Uribe Mora"
        };

        static void Main(string[] args)
        {
            Console.OutputEncoding = System.Text.Encoding.UTF8;

            // =============================================================
            //   MINISTERIO DE SALUD - CAMPAÑA VACUNACIÓN COVID-19
            // =============================================================

            // ── CONJUNTO U: Universo – 500 ciudadanos ──────────────────
            HashSet<string> universo = new HashSet<string>(CIUDADANOS_ECUADOR);

            // ── CONJUNTO A: Vacunados con Pfizer – primeros 75 ─────────
            HashSet<string> pfizer = new HashSet<string>(CIUDADANOS_ECUADOR.Take(75));

            // ── CONJUNTO B: Vacunados con AstraZeneca – posiciones 51-125
            //    (solapamiento intencional en posiciones 51-75 → ambas dosis)
            HashSet<string> astrazeneca = new HashSet<string>(CIUDADANOS_ECUADOR.Skip(50).Take(75));

            // =============================================================
            //   OPERACIONES DE TEORÍA DE CONJUNTOS
            // =============================================================

            // 1. NO VACUNADOS → U \ (A ∪ B)
            HashSet<string> union = new HashSet<string>(pfizer);
            union.UnionWith(astrazeneca);
            HashSet<string> noVacunados = new HashSet<string>(universo);
            noVacunados.ExceptWith(union);

            // 2. AMBAS DOSIS → A ∩ B
            HashSet<string> ambasDosis = new HashSet<string>(pfizer);
            ambasDosis.IntersectWith(astrazeneca);

            // 3. SOLO PFIZER → A \ B
            HashSet<string> soloPfizer = new HashSet<string>(pfizer);
            soloPfizer.ExceptWith(astrazeneca);

            // 4. SOLO ASTRAZENECA → B \ A
            HashSet<string> soloAstraZeneca = new HashSet<string>(astrazeneca);
            soloAstraZeneca.ExceptWith(pfizer);

            // =============================================================
            //   RESULTADOS
            // =============================================================
            Separador('=', 70);
            CentrarTexto("MINISTERIO DE SALUD DEL ECUADOR", 70);
            CentrarTexto("CAMPAÑA NACIONAL DE VACUNACIÓN COVID-19", 70);
            CentrarTexto("REPORTE DE CONJUNTOS", 70);
            Separador('=', 70);

            Console.WriteLine();
            Console.WriteLine("  RESUMEN DE CONJUNTOS BASE:");
            Console.WriteLine($"    Universo total ciudadanos (U)    : {universo.Count,4}");
            Console.WriteLine($"    Vacunados con Pfizer     (A)     : {pfizer.Count,4}");
            Console.WriteLine($"    Vacunados con AstraZeneca (B)    : {astrazeneca.Count,4}");

            MostrarListado(@"1) CIUDADANOS NO VACUNADOS  -->  U \ (A U B)", noVacunados);
            MostrarListado(@"2) CIUDADANOS CON AMBAS DOSIS  -->  A n B", ambasDosis);
            MostrarListado(@"3) CIUDADANOS SOLO CON PFIZER  -->  A \ B", soloPfizer);
            MostrarListado(@"4) CIUDADANOS SOLO CON ASTRAZENECA  -->  B \ A", soloAstraZeneca);

            Separador('=', 70);
            Console.WriteLine("  VERIFICACIÓN (debe sumar 500):");
            int suma = noVacunados.Count + ambasDosis.Count + soloPfizer.Count + soloAstraZeneca.Count;
            Console.WriteLine($"    {noVacunados.Count} + {ambasDosis.Count} + {soloPfizer.Count} + {soloAstraZeneca.Count} = {suma} ✓");
            Separador('=', 70);
        }

        static void MostrarListado(string titulo, HashSet<string> conjunto)
        {
            Console.WriteLine();
            Separador('─', 70);
            Console.WriteLine($"  {titulo}");
            Console.WriteLine($"  Total: {conjunto.Count} ciudadano(s)");
            Separador('─', 70);

            var lista = conjunto.OrderBy(x => x).ToList();
            for (int i = 0; i < lista.Count; i++)
            {
                // Dos columnas
                Console.Write($"  {i + 1,3}. {lista[i],-32}");
                if ((i + 1) % 2 == 0 || i == lista.Count - 1)
                    Console.WriteLine();
            }
        }

        static void Separador(char car, int largo) =>
            Console.WriteLine(new string(car, largo));

        static void CentrarTexto(string texto, int ancho)
        {
            int espacios = (ancho - texto.Length) / 2;
            Console.WriteLine(new string(' ', Math.Max(0, espacios)) + texto);
        }
    }
}



